POST http://localhost:8080/jobe/index.php/restapi/runs
Content-Type: application/json
X-API-KEY: gQhxy1g8B0ZTVjYfWDjpPNgEoAD6iEm6CdKoDbfC9bZPqBpRvNw_r_f10rcfQU3skRZscSF2bflwlFK0i9DvOg==

{
    "run_spec":{
        "language_id":"python3",
        "sourcefilename":"index.py",
        "sourcecode":"def sol():\n\tprint(30)\nsol()"
    }
}