POST http://localhost:8080/jobe/index.php/restapi/runs
Content-Type: application/json
X-API-KEY: gQhxy1g8B0ZTVjYfWDjpPNgEoAD6iEm6CdKoDbfC9bZPqBpRvNw_r_f10rcfQU3skRZscSF2bflwlFK0i9DvOg==

{
    "run_spec":{
        "language_id":"nodejs",
        "sourcefilename":"script.js",
        "sourcecode":"console.log(30)",
        "memorylimit":4000
    }
}